spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://mysql:3306/transaction_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: transaction-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap

    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

account:
  service:
    url: http://account-service:8081

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
