spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379


  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Account-service routes
            - id: account-service
              uri: http://account-service:8081
              predicates:
                - Path=/api/v1/accounts/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@keyResolver}"


            # Transaction-service routes
            - id: transaction-service
              uri: http://transaction-service:8082
              predicates:
                - Path=/api/v1/transactions/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@keyResolver}"

            # Payment-service routes
            - id: payment-service
              uri: http://payment-service:8083
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    key-resolver: "#{@keyResolver}"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway