spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://mysql:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8083

#RazorPay Configuration

razorpay:
  key-id: rzp_test_Td4go8B00IhKR6
  key-secret: YyGwXR7paLJmGqLdrcYrJSQQ
  webhook-secret :

management:
  endpoints:
    web:
      exposure:
        include: health,info

