spring:
  application:
    name: fraud-detection-service
  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


fraud:
  max-transactions-per-minute: 5
  suspicious-amount-multiplier: 5
  max-balance-percentage-allowed: 90

server:
  port: 8084

#Account Service url for feign client
account:
  service:
    url: http://account-service:8081


management:
  endpoints:
    web:
      exposure:
        include: health,info
